#!/usr/bin/env python3

from pathlib import Path
import json

data = {}

try:
    with open(Path.home() / ".local/share/chezmoi/.chezmoidata.json") as cd:
        data = json.load(cd)["cys"]
except FileNotFoundError:
    pass

# Read machine name.
if "machine" not in data:
    machine_path = Path("/sys/devices/virtual/dmi/id/product_name")
    if machine_path.is_file():
        with open(machine_path, "r") as f:
            data["machine"] = f.read().strip()
if "machine" not in data:
    machine_path = Path("/proc/device-tree/model")
    if machine_path.is_file():
        with open(machine_path, "r") as f:
            data["machine"] = f.read().strip().rstrip("\u0000")
if "machine" not in data:
    data["machine"] = input("which machine are you using? ")

with open("/etc/hostname") as f:
    data["hostname"] = f.read().strip()

if data["machine"] == "HP EliteBook 755 G5" and data[
        "hostname"] == "pretty-arch":
    data["desktop"] = "KDE"

if "location" not in data.keys():
    data["location"] = input("where are you? ")

with open(Path.home() / ".local/share/chezmoi/.chezmoidata.json", "w") as f:
    json.dump({"cys": data}, f)
