#!/usr/bin/env python3

from pathlib import Path
import json
import subprocess

data = {}
data_path = Path.home() / ".local/share/chezmoi/chezmoidata.json"

try:
    with open(data_path, "r") as cd:
        data = json.load(cd)["cys"]
except FileNotFoundError:
    pass

# Read machine name.
if "machine" not in data:
    machine_path = Path("/sys/devices/virtual/dmi/id/product_name")
    if machine_path.is_file():
        with open(machine_path, "r") as f:
            data["machine"] = f.read().strip()
if "machine" not in data:
    machine_path = Path("/proc/device-tree/model")
    if machine_path.is_file():
        with open(machine_path, "r") as f:
            data["machine"] = f.read().strip().rstrip("\u0000")
if "machine" not in data:
    data["machine"] = input("which machine are you using? ").strip()

hostname_path = Path("/etc/hostname")
if hostname_path.is_file():
    with open(hostname_path) as f:
        data["hostname"] = f.read().strip()
else:
    result = subprocess.run(["hostname"], capture_output=True, text=True)
    if result.returncode == 0:
        data["hostname"] = result.stdout.strip()
    else:
        data["hostname"] = input("what is your current hostname? ").strip()

if (data["machine"] == "HP EliteBook 755 G5"
        and data["hostname"] == "pretty-arch"):
    data["desktop"] = "KDE"
else:
    data["desktop"] = ""

if "location" not in data.keys():
    data["location"] = input("where are you? ")

with open(data_path, "w") as f:
    json.dump({"cys": data}, f)
