#!/usr/bin/zsh

if [ -n "$PATH_FOR_MAC" ]; then
  export PATH="$PATH_FOR_MAC"
fi

if [ -n "$USE_FISH" ] && which fish >/dev/null 2>&1; then
  exec fish
fi

# Always prefer alacritty-direct.
if [ "$TERM" = "alacritty" ]; then
  export TERM=alacritty-direct
fi

source $XDG_CONFIG_HOME/sh/aliases.sh
source $XDG_CONFIG_HOME/sh/functions.sh

# Prompt.
PROMPT="[%n@%M %~]$ "

# options
setopt No_Beep

zcmpl () {
  for f in 'zshenv' 'zprofile' 'zshrc' 'zlogin' 'zlogout'
  do
    if [[ -e "$ZDOTDIR/.$f" ]]
    then
      zcompile "$ZDOTDIR/.$f"
    fi
  done
}
