port: 7890
socks-port: 7891
external-controller: localhost:9090
allow-lan: true
ipv6: true

profiles:
  store-selected: true
clash-for-android:
  append-system-dns: false

dns:
  enable: true
  default-nameserver:
    - 1.1.1.1
  ipv6: true
  enhanced-mode: fake-ip
  nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 208.67.222.222
  fake-ip-filter:
    - "*.local"

# TUN requires elevated permissions.
#
# On Linux, run `sudo setcap cap_net_admin=eip /path/to/clash-meta/kernel`.
#
# On macOS, run `sudo chown root:admin /path/to/clash-meta/kernel` 
# and `sudo chmod +s /path/to/clash-meta/kernel`.
tun:
  enable: true
  stack: mixed
  auto-route: true
  auto-detect-interface: true

geox-url:
  geoip: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat
  geosite: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat
  mmdb: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.metadb
geo-auto-update: true
geo-update-interval: 24

mode: rule

log-level: info
